target-version = "py310"

[lint]
select = [
  "A",      # warn about shadowing built-ins
  "B",      # flake8-bugbear
  "C4",     # flake8-comprehensions
  "COM",    # flake8-commas
  "D",      # pydocstyle
  "DOC",    # pydoclint
  "E",      # pycodestyle errors
  "EM",     # flake8-errmsg
  "F",      # pyflakes
  "FA",     # flake8-future-annotations
  "I",      # isort
  "ICN",    # flake8-import-conventions
  "ISC",    # flake8-implicit-str-concat
  "N",      # pep8-naming
  "NPY",    # NumPy-specific rules
  "PERF",   # Perflint
  "PT",     # flake8-pytest-style
  "RUF",    # Ruff-specific
  "S",      # flake8-bandit
  "SIM",    # flake8-simplify
  "TCH",    # flake8-type-checking
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
]
ignore = [
  # recommended ignores per ruff
  "W191",   # tab-indentation
  "E111",   # indentation-with-invalid-multiple
  "E114",   # indentation-with-invalid-multiple-comment
  "E117",   # over-indented
  "D206",   # indent-with-spaces
  "D300",   # triple-single-quotes
  "COM812", # missing-trailing-comma
  "COM819", # prohibited-trailing-comma
  "ISC001", # single-line-implicit-string-concatenation
  "ISC002", # multi-line-implicit-string-concatenation
  # others
  "E741",   # ambiguous-variable-name
]

[lint.per-file-ignores]
"tests/*" = ["S101"]
"__init__.py*" = ["F401"]
"typings/*" = ["N801", "N803"]

[lint.pydocstyle]
convention = "google"

[format]
docstring-code-format = true
